version: '3.9'
services:
  api:
    build: ./src/Backend/MLGpsCleaner.Api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Traccar=server=mysql;port=3306;database=traccar;user=root;password=;TreatTinyAsBoolean=false
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=traccar
    ports:
      - "3306:3306"
    volumes:
      - traccar_data:/var/lib/mysql
  frontend:
    build: ./src/Frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  traccar_data:
